name: Build LaTeX document
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Debug - list repository files
        run: |
          pwd
          ls -la
          echo "Listing Presentazione2cfu:"
          ls -la Presentazione2cfu || true
          find . -maxdepth 3 -type f -name '*.tex' -print

      - name: Install custom beamer theme (if present)
        run: |
          if [ -f Presentazione2cfu/beamerthemepolimi.sty ]; then
            echo "Found local beamerthemepolimi.sty — installing to TEXMFHOME"
            mkdir -p $HOME/texmf/tex/latex/polimi
            cp Presentazione2cfu/beamerthemepolimi.sty $HOME/texmf/tex/latex/polimi/
          else
            echo "No local beamerthemepolimi.sty found in repo."
          fi
          # Make $HOME/texmf visible to TeX
          echo "TEXINPUTS=.:$HOME/texmf/tex/latex//:" >> $GITHUB_ENV

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Presentazione2cfu/main.tex
